matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

language: go
go:
  - "1.10"

addons:
  apt:
    packages:
      - gfortran

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo --version

install:
  - go generate
  - export CGO_LDFLAGS_ALLOW="-Wl*"

script:
  - go build
  - go test
